name: st_manager
description: ST Manager 2.0.1
publish_to: "none"

version: 2.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.14
  firebase_analytics: ^10.8.10

  # Storage
  flutter_secure_storage: ^9.0.0

  # Permissions
  permission_handler: ^11.3.1

  # RouterOS API
  routeros_api: ^0.1.4

  # HTTP
  http: ^1.2.0

  # Path
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
    - assets/logo/logo.png